import re
import typer
from xmlrpc.client import Boolean
from bs4 import BeautifulSoup
from urllib.parse import urljoin
import time
from datetime import date as datelib
from concurrent.futures import ThreadPoolExecutor, ProcessPoolExecutor
import asyncio
from pathlib import Path
import sqlite3 as sql
import os
from multiprocess import Pool
import ndjson
import tqdm
from shutil import rmtree
import unicodedata




class Extractor:
    """
    A class for extracting data from files and storing it in the target folder.

    Parameters:
        target_folder_path: str
            The path to the folder where the extracted data is stored.
        use_sqlite: bool, optional
            Whether or not to use SQLite to store the extracted data. Default is False.
        extractor_delete_files: bool, optional
            Whether or not to delete the original files after extracting data. Default is False.
        file_extractor: FileExtractor, optional
            An custom instance of a FileExtractor class used to extract data from files. Default is None, in which case it will use the default FileExtractor class.

    Methods:
        _create_results(path)
            Extracts the data from one specific file
        extract_companies()
            Start the extracting of all data from the files
    """

    def __init__(
        self, target_folder_path, date=str(datelib.today())
    ):
        self.target_folder_path = target_folder_path
        self.files_process 


        [id, domain, all_text?, page/kvk, page/btw..., meta_encoding, meta_generator, webshop, "kvk": [], "btw": [], "phone": [], "email": [], "fax": []]

        "relevant_content"


    def default_page?
{"id": "01125149",
  "domain": "frieslandbouwdetachering.nl", 
  "level": "0", 
  "website": "https://www.frieslandbouwdetachering.nl/",
    "date": "2023-03-10", 
    "path": "../../output_data/data/01125149/frieslandbouwdetachering.nl/2023-03-10/www.frieslandbouwdetachering.nl", 
    "meta_encoding": "utf-8", "meta_viewport": "width=device-width, initial-scale=1.0, maximum-scale=1.0", "annual_reports": [], "kvk": [], "btw": [], "phone": [], "email": [], "fax": [], "text": "Web Server's Default Page\nWeb Server's Default Page\nThis page is generated by\nPlesk\n, the leading hosting automation software. You see this page because there is no Web site at this address.\nYou can do the following:\nCreate domains and set up Web hosting using Plesk.\nWhat is Plesk\nPlesk\nis a hosting\ncontrol panel\nwith simple and secure web server and website management tools. It was specially designed to help IT specialists manage web, DNS, mail and other services through a comprehensive and user-friendly GUI.\nLearn more about Plesk\n.\nDeveloper Blog\nForum\nKnowledge Base\nFacebook\nTwitter\nLinkedIn\nThis page was generated by Plesk. Plesk is the leading WebOps platform to run, automate and grow applications, websites and hosting businesses. Learn more at\nplesk.com\n.", "zipcode": [], "address": []}

    
                            
            file_res = (
                        self.target_folder_path
                        / "scraped_data"
                        / (
                            "scraped_data_"
                            + str(datelib.today())
                            + f"_{i}-{i+n}.ndjson"
                        )
                    )